export const specialOffers = [
  {
    id: 1,
    name: "گوشی هوشمند سامسونگ",
    price: 12500000,
    discount: 10,
    imageUrl: ["/images/special-offer/phone.png"],
  },
  {
    id: 2,
    name: "هدفون بی‌سیم",
    price: 850000,
    discount: 14,
    imageUrl: ["/images/special-offer/a1.png"],
  },
  {
    id: 3,
    name: "ساعت هوشمند",
    price: 1450000,
    discount: 20,
    imageUrl: ["/images/special-offer/watch.png"],
  },
  {
    id: 4,
    name: "تلویزیون ۴۰ اینچ",
    price: 8500000,
    discount: 17,
    imageUrl: ["/images/special-offer/tv.png"],
  },
  {
    id: 5,
    name: "لپ‌تاپ ایسوس",
    price: 28500000,
    discount: 30,
    imageUrl: ["/images/special-offer/surface.png"],
  },
  {
    id: 6,
    name: "کنسول بازی PS5",
    price: 24000000,
    discount: 27,
    imageUrl: ["/images/special-offer/ps.png"],
  },
  {
    id: 7,
    name: "دوربین عکاسی کانن",
    price: 19500000,
    discount: 11,
    imageUrl: ["/images/special-offer/camera.png"],
  },
  {
    id: 8,
    name: "جاروبرقی رباتیک",
    price: 6900000,
    discount: 10,
    imageUrl: ["/images/special-offer/vacuum.png"],
  },
];

export const setStyle = [
  {
    id: 1,
    name: "تونیک زنانه مدل 606",
    price: 12500000,
    discount: 10,
    imageUrl: ["/images/set/1.png"],
  },
  {
    id: 2,
    name: "تونیک زنانه اسمارا مدل 44-46",
    price: 850000,
    discount: 14,
    imageUrl: ["/images/set/2.png"],
  },
  {
    id: 3,
    name: "تونیک بافت زنانه اسمارا مدل 2429",
    price: 1450000,
    discount: 20,
    imageUrl: ["/images/set/3.png"],
  },
  {
    id: 4,
    name: "زیرسارافونی نخی زنانه با طرح ساده و رنگ مشکی، مدل SA2",
    price: 8500000,
    discount: 17,
    imageUrl: ["/images/set/4.png"],
  },
  {
    id: 5,
    name: "تونیک زنانه اسمارا مدل S2137",
    price: 28500000,
    discount: 30,
    imageUrl: ["/images/set/5.png"],
  },
  {
    id: 6,
    name: "تونیک نخی زنانه اسمارا با طرح گل‌دار و رنگ آبی، مدل LS237",
    price: 24000000,
    discount: 27,
    imageUrl: ["/images/set/6.png"],
  },
  {
    id: 7,
    name: "تونیک زنانه اسمارا مدل B2022",
    price: 19500000,
    discount: 11,
    imageUrl: ["/images/set/7.png"],
  },
  {
    id: 8,
    name: "تونیک زنانه اسمارا مدل 44-46",
    price: 6900000,
    discount: 19,
    imageUrl: ["/images/set/8.png"],
  },
  {
    id: 9,
    name: "تونیک زنانه مدل M3368",
    price: 8900000,
    discount: 11,
    imageUrl: ["/images/set/9.png"],
  },
  {
    id: 10,
    name: "تونیک بافت زنانه اسمارا با طرح ساده و رنگ طوسی، مدل کبریتی",
    price: 9900000,
    discount: 14,
    imageUrl: ["/images/set/10.png"],
  },
];
