export const bankOptions = [
  { label: "بانک ملی", value: "melli" },
  { label: "بانک ملت", value: "mellat" },
  { label: "بانک سپه", value: "sepah" },
  { label: "بانک صادرات", value: "saderat" },
  { label: "بانک کشاورزی", value: "keshavarzi" },
  { label: "بانک مسکن", value: "maskan" },
  { label: "بانک تجارت", value: "tejarat" },
  { label: "بانک رفاه", value: "refah" },
  { label: "بانک گردشگری", value: "gardeshgari" },
  { label: "بانک پست بانک", value: "postbank" },
  { label: "بانک توسعه تعاون", value: "taavon" },
  { label: "بانک صنعت و معدن", value: "sanatmadan" },
  { label: "بانک قرض الحسنه مهر", value: "mehr" },
  { label: "بانک سینا", value: "sina" },
  { label: "بانک سرمایه", value: "sarmayeh" },
  { label: "بانک شهر", value: "shahr" },
  { label: "بانک دی", value: "day" },
  { label: "بانک صادرات ایران", value: "saderatiran" },
  { label: "بانک ایران زمین", value: "iranZamin" },
  { label: "بانک خاورمیانه", value: "khavarmiyaneh" },
];
