export const test=  {
    name: "یخچال و فریزر مدل ArcticCool 2024",
    price: 28900000,
    originalPrice: 34000000,
    discount: 15,
    imageUrl: ["/images/menu/home-applliance/electronic/free.png"],
    colorsAvailable: ["نقره‌ای", "سفید"],
    sizesAvailable: ["28 فوت"],
    category: "آرایشی و بهداشتی",
    subcategory: "لوازم خانگی برقی",
    type: "ترازو",
    productCode: "HAE101",
    description:
      "یخچال و فریزر ساید بای ساید با فناوری سرمایش سریع و مصرف انرژی بهینه.",
    brand: "آرتیک",
    stock: 10,
    views: 1250,
    sales: 320,
    createdAt: "2024-04-10T10:00:00Z",
    material: "استیل ضدزنگ",
    gender: "همه",
    ageRange: "بزرگسال",
    pattern: "ساده",
    reviews: [
      {
        id: "r301",
        username: "میلاد",
        rating: 5,
        comment: "فضای داخلی جادار و طراحی مدرن داره، بسیار راضیم.",
        date: "2024-04-12T08:45:00Z",
      },
      {
        id: "r302",
        username: "مریم",
        rating: 4,
        comment: "صدای کمی داره و خنک‌کنندگیش عالیه، فقط قیمتش کمی بالاست.",
        date: "2024-04-13T14:20:00Z",
      },
    ],
  }